"""empty message

Revision ID: 2fe4e90e8876
Revises: b261744318c1
Create Date: 2018-09-13 15:31:45.281478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fe4e90e8876'
down_revision = 'b261744318c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_vsppm_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('admin', sa.String(length=60), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_column('tbl_vsppm_department', 'parent')
    op.drop_column('tbl_vsppm_department', 'grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_vsppm_department', sa.Column('grade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('tbl_vsppm_department', sa.Column('parent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_table('tbl_vsppm_group')
    # ### end Alembic commands ###
