"""empty message

Revision ID: 8a6acf4cc6ae
Revises: 2fe4e90e8876
Create Date: 2018-09-14 09:00:19.030758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a6acf4cc6ae'
down_revision = '2fe4e90e8876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_vsppm_group_user',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['tbl_vsppm_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_vsppm_user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_vsppm_group_user')
    # ### end Alembic commands ###
