"""empty message

Revision ID: d6600251718c
Revises: 3d8fa92d948e
Create Date: 2018-09-17 11:26:09.355739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6600251718c'
down_revision = '3d8fa92d948e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_vsppm_project', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('tbl_vsppm_project', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_vsppm_project', 'tbl_vsppm_department', ['department_id'], ['id'])
    op.create_foreign_key(None, 'tbl_vsppm_project', 'tbl_vsppm_company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_vsppm_project', type_='foreignkey')
    op.drop_constraint(None, 'tbl_vsppm_project', type_='foreignkey')
    op.drop_column('tbl_vsppm_project', 'department_id')
    op.drop_column('tbl_vsppm_project', 'company_id')
    # ### end Alembic commands ###
