"""empty message

Revision ID: eb172ac2708b
Revises: 
Create Date: 2018-09-12 15:13:30.807746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb172ac2708b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_vsppm_acl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=128), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_vsppm_department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('admin', sa.String(length=60), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_vsppm_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_vsppm_role_acl',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('acl_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['acl_id'], ['tbl_vsppm_acl.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_vsppm_role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'acl_id')
    )
    op.create_table('tbl_vsppm_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('real_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['tbl_vsppm_department.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_vsppm_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tbl_vsppm_user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_vsppm_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_vsppm_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_vsppm_user_role')
    op.drop_table('tbl_vsppm_user')
    op.drop_table('tbl_vsppm_role_acl')
    op.drop_table('tbl_vsppm_role')
    op.drop_table('tbl_vsppm_department')
    op.drop_table('tbl_vsppm_acl')
    # ### end Alembic commands ###
