"""empty message

Revision ID: f730fd3b0af3
Revises: 8a6acf4cc6ae
Create Date: 2018-09-14 16:14:54.444697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f730fd3b0af3'
down_revision = '8a6acf4cc6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_vsppm_user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tbl_vsppm_user', 'tbl_vsppm_company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_vsppm_user', type_='foreignkey')
    op.drop_column('tbl_vsppm_user', 'company_id')
    # ### end Alembic commands ###
